name: mayavi_env
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py=2.1.0=py39hca03da5_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.18=py39hefdd603_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - apptools=5.3.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=py_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.0.9=py39h313beb8_9
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=py_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.4.26=py39hca03da5_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - configobj=5.0.9=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h85b62ae_2
  - cpython=3.9.22=py39hd8ed1ab_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h60b93bd_7
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.13.18=h8280c03_0
  - debugpy=1.8.14=py39h941272d_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h286801f_0
  - eigen=3.4.0=h1995070_0
  - envisage=7.0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.0=h286801f_0
  - ffmpeg=7.1.1=gpl_h20db955_105
  - filelock=3.18.0=pyhd8ed1ab_0
  - flatbuffers=24.12.23=h28594ff_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py39hefdd603_0
  - freetype=2.13.3=hce30654_1
  - fribidi=1.0.10=h27ca646_0
  - frozenlist=1.6.0=py39h025a298_0
  - gast=0.5.3=pyhd3eb1b0_0
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - giflib=5.2.2=h80987f9_0
  - gl2ps=1.4.2=hc97c1ff_1
  - glew=2.1.0=h9f76cd9_2
  - glib=2.84.0=heee381b_0
  - glib-tools=2.84.0=h1dc7a0c_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py39h478d0be_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.13=hebf3989_1003
  - grpcio=1.67.1=py39h7cb28a9_2
  - gst-plugins-base=1.24.11=h3c5c1d0_0
  - gstreamer=1.24.11=hfe24232_0
  - h5py=3.13.0=nompi_py39h54144e7_101
  - harfbuzz=11.1.0=hab40de2_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.6=nompi_ha698983_101
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.0=pyhd8ed1ab_0
  - jsoncpp=1.9.6=h726d253_1
  - jsonschema=4.23.0=py39hca03da5_0
  - jsonschema-specifications=2023.7.1=py39hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keras=3.6.0=py39hca03da5_0
  - kiwisolver=1.4.7=py39h157d57c_0
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libaec=1.1.3=hebf3989_0
  - libass=0.17.3=h68e5b86_2
  - libblas=3.9.0=31_h10e41b3_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libclang-cpp17=17.0.6=default_hf90f093_8
  - libclang-cpp18.1=18.1.8=default_hf90f093_9
  - libclang13=20.1.4=default_hee4fbb3_0
  - libcurl=8.13.0=h73640d1_0
  - libcxx=20.1.4=ha82da77_1
  - libdeflate=1.23=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.84.0=hdff4504_0
  - libgrpc=1.67.1=h0a426d6_2
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libiconv=1.18=hfe07756_1
  - libintl=0.24.1=h493aca8_0
  - libintl-devel=0.24.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - libllvm11=11.1.0=hfa12f05_5
  - libllvm14=14.0.6=hd1a9a77_4
  - libllvm17=17.0.6=hc4b4ae8_3
  - libllvm18=18.1.8=hc4b4ae8_3
  - libllvm20=20.1.4=h598bca7_0
  - liblzma=5.8.1=h39f12f2_1
  - liblzma-devel=5.8.1=h39f12f2_1
  - libnetcdf=4.9.2=nompi_h3352478_117
  - libnghttp2=1.64.0=h6d7220d_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.29=hea593b9_0
  - libopenvino=2025.0.0=h3f17238_2
  - libopenvino-arm-cpu-plugin=2025.0.0=h3f17238_2
  - libopenvino-auto-batch-plugin=2025.0.0=h7f72211_2
  - libopenvino-auto-plugin=2025.0.0=h7f72211_2
  - libopenvino-hetero-plugin=2025.0.0=h718ad69_2
  - libopenvino-ir-frontend=2025.0.0=h718ad69_2
  - libopenvino-onnx-frontend=2025.0.0=h76e6831_2
  - libopenvino-paddle-frontend=2025.0.0=h76e6831_2
  - libopenvino-pytorch-frontend=2025.0.0=h286801f_2
  - libopenvino-tensorflow-frontend=2025.0.0=he275e1d_2
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h286801f_2
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.47=h3783ad8_0
  - libpq=17.4=h6896619_1
  - libprotobuf=5.28.3=h3bd63a1_1
  - libre2-11=2024.07.02=h07bc746_2
  - librsvg=2.58.4=h266df6f_3
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.49.2=h3f77e49_0
  - libssh2=1.11.1=h1590b86_0
  - libtheora=1.1.1=h99b78c6_1006
  - libtiff=4.7.0=h551f018_4
  - libusb=1.0.28=h48c0fde_1
  - libvorbis=1.3.7=h9f76cd9_0
  - libvpx=1.14.1=h7bae524_0
  - libwebp=1.5.0=h1618228_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.8=h52572c6_0
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=15.0.7=h7cfbb63_0
  - llvmlite=0.39.1=py39h8ca5d33_1
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.10.0=h286801f_1
  - markdown=3.8=py39hca03da5_0
  - markdown-it-py=2.2.0=py39hca03da5_1
  - markupsafe=3.0.2=py39h80987f9_0
  - matplotlib=3.9.4=py39hdf13c20_0
  - matplotlib-base=3.9.4=py39h7251d6c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mayavi=4.8.3=pyqt_py39hcb557e2_301
  - mdurl=0.1.0=py39hca03da5_0
  - ml_dtypes=0.4.1=py39h6e33161_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py39h157d57c_0
  - multidict=6.4.3=py39hafbbd28_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=hd7719f6_6
  - mysql-libs=9.0.1=ha8be5b7_6
  - namex=0.0.7=py39hca03da5_0
  - narwhals=1.31.0=py39hca03da5_1
  - nbformat=5.10.4=py39hca03da5_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - nlohmann_json=3.12.0=ha1acc90_0
  - nspr=4.36=h5833ebf_0
  - nss=3.111=ha3c76ea_0
  - numba=0.56.4=py39h251cc7c_0
  - numpy=1.23.5=py39hefdcf20_0
  - openh264=2.6.0=h514c7bf_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openldap=2.6.9=hbe55e7a_0
  - openssl=3.5.0=h81ee809_1
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.14.1=py39h48ca7d4_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.3=h5fd7515_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.44=ha881caa_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.2.1=py39hfea3036_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.0=h2f9eb0b_0
  - platformdirs=4.3.8=pyhe01879c_0
  - plotly=6.1.2=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - proj=9.6.0=h1318a7e_1
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py39hefdd603_0
  - protobuf=5.28.3=py39h941272d_0
  - psutil=7.0.0=py39hf3bc14e_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyface=8.0.0=pyhd8ed1ab_2
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.11=py39h4e308d9_0
  - pyqt5-sip=12.17.0=py39h941272d_0
  - pysocks=1.7.1=py39hca03da5_0
  - python=3.9.22=hdec7a8b_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.20.0=py39hca03da5_0
  - python-flatbuffers=24.3.25=py39hca03da5_0
  - python_abi=3.9=7_cp39
  - pytorch=2.5.1=py3.9_0
  - pyyaml=6.0.2=py39hefdd603_2
  - pyzmq=26.4.0=py39h80d5f2a_0
  - qhull=2020.2=h420ef59_5
  - qt-main=5.15.15=h67564f6_3
  - qt6-main=6.9.0=h1b8e88b_2
  - re2=2024.07.02=h6589ca4_2
  - readline=8.2=h1d1bf99_2
  - referencing=0.30.2=py39hca03da5_0
  - requests=2.32.3=py39hca03da5_1
  - rich=13.9.4=py39hca03da5_0
  - rpds-py=0.22.3=py39h2aea54e_0
  - scikit-learn=1.3.1=py39h2a74614_0
  - scipy=1.13.1=py39h3d5391c_0
  - sdl2=2.32.54=ha1acc90_0
  - sdl3=3.2.14=hf196eef_0
  - setuptools=80.1.0=pyhff2d567_0
  - sip=6.10.0=py39h941272d_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h98b9ce2_1
  - sqlite=3.49.2=hd7222ec_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.0.2=h8ab69cd_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=h8149167_1
  - tbb-devel=2021.13.0=hf29b1df_1
  - tensorboard=2.18.0=py39hca03da5_0
  - tensorboard-data-server=0.7.0=py39ha6e5c4f_1
  - tensorflow=2.18.0=cpu_py39h0355d61_0
  - tensorflow-base=2.18.0=cpu_py39h1359435_0
  - tensorflow-estimator=2.18.0=cpu_py39h4af9f6e_0
  - termcolor=2.1.0=py39hca03da5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h5083fa2_1
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchaudio=2.5.1=py39_cpu
  - torchvision=0.20.1=py39_cpu
  - tornado=6.4.2=py39hf3bc14e_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - traits=7.0.2=py39hf3bc14e_0
  - traitsui=8.0.0=pyhd8ed1ab_1
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py39hf3bc14e_0
  - urllib3=2.3.0=py39hca03da5_0
  - utfcpp=4.0.6=h54c0426_0
  - vtk=9.4.2=he19685a_0
  - vtk-base=9.4.2=py39h54658bf_0
  - vtk-io-ffmpeg=9.4.2=h73aca5d_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - werkzeug=3.1.3=py39hca03da5_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.0=py39h80987f9_0
  - wslink=2.3.3=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_1
  - xz-gpl-tools=5.8.1=h9a6d368_1
  - xz-tools=5.8.1=h39f12f2_1
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.20.0=py39hefdd603_0
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - imageio==2.37.0
      - ipympl==0.9.7
      - ipywidgets==8.1.7
      - jupyterlab-widgets==3.0.15
      - lazy-loader==0.4
      - scikit-image==0.24.0
      - symfit==0.5.6
      - tifffile==2024.8.30
      - toposort==1.10
      - widgetsnbextension==4.0.14
prefix: /opt/anaconda3/envs/mayavi_env
